### ISSUE TITLE
Exclude "tests" package from distribution

### ISSUE THREAD

**Issue by nik123** [levii/dataclass-type-validator#21]
In my project I have `tests` folder. In python modules, located in `tests` folder I do have several imports:

```
# tests/bar.py
from tests import foo
```

However, after I execute `pip install dataclass-type-validator`, I can no longer import any module from my "tests" folder because my "tests" folder is overriden in `sys.path` with `dataclass-type-validator` tests folder. Here is piece of code to check it:

```
import tests

print(tests.__path__)
```

Before installation of `dataclass-type-validator` code yields "/path/to/my/project/tests". After installation of `dataclass-type-validator` it yields `path/to/my/project/venv/lib/python3.8/site-packages/tests`

**Solution**

I guess `find_packages(exclude=["tests"])` will be enough to solve the issue.

**Comment by akiray03** [comment]
@nik123 Thank you for your contributions!
Released: https://pypi.org/project/dataclass-type-validator/0.1.2/
